### ISSUE TITLE
browser vendor meetings

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/charter-html#10] opened 2015-04-28 20:33 UTC
> Team will hold quaterly meetings with those with authority over what gets committed to a consumer browser engine codebase. The scheduling, agenda, and summary of those meetings will be made available to the W3C Membership. 

spelling: 'quaterly'

why will results of meetings not be public?

**Comment by marcoscaceres** [comment] 2015-04-28 20:47
Indeed, I guess that's an oversight?

**Comment by LJWatson** [comment] 2015-05-02 08:49
Created a PR yesterday to fix this spelling mistake (and another in the same section).

+1 to meeting outcomes/minutes being made public.

**Comment by rubys** [comment] 2015-05-02 15:04
Spelling out the disconnect between this item and #2:
- To ensure proper focus and prioritarization, the W3C Team will ensure proper sychronization of vendor interests.
- Chairs need to ensure that bugs get property triaged, prioritized, and addressed

Pick one.  Either the team is responsible for prioritization or the chairs are, or they jointly are.  If it follows that a F2F meeting is helpful to make this happen, then all of those responsible for prioritization should make a determination as to who should attend.  My recommendation is that the plan does not prescribe up front who may attend as that may evolve over time, may vary meeting to meeting, or may vary within a meeting (example: two day meeting, the first day is limited attendance, the second day is open).

To be clear: I personally recommend open meetings and open minutes; but I've been overruled in the past on this matter.  Accordingly, @marcoscaceres, I do NOT believe that this is an oversight, but do very much believe that this is a bug.

**Comment by plehegar** [comment] 2015-05-15 20:14
@marcoscaceres @rubys re public or not. It wasn't an oversight but this got changed following an AB discussion las week. It now says that minutes will be public.
There is still the disconnect pointed out by @rubys to address.

**Comment by plehegar** [comment] 2015-05-20 20:06
Given the recent AC discussion on this topic, I believe it would be better to drop that section out of the plan and resolve it separately. At the minimum, it will need a better framing to be brought again.

**Comment by lehors** [comment] 2015-05-22 18:23
I have to admit to be puzzled by Philippe's proposal to remove from the plan the idea of having quarterly meetings altogether. The problem has never been about having meetings to discuss priorities with interested parties, the problem is about having these meetings behind closed doors with merely a few selected people.

What would removing this from the plan mean? That the need wasn't real? Or that the meetings will just take place anyway, under the radar?

The reason behind the idea of having quaterly meetings with the browser vendors was the lack of active participation from these companies in the HTML WG. I don't think anyone disagrees that this is a serious issue that deserves to be addressed. Hosting meetings to discuss what it would take to get them interested is totally reasonable. Generalizing this to having regular meetings to discuss whether the WG is still relevant and on track to deliver something that is really useful to the browser vendors and the industry at large is also totally reasonable. All that is needed is for these meetings to be open and transparent. This means being announced publically (to the AC at least) and to be open to all interested parties (at least all members).

The stated goal for the proposed browser meetings was to assess priority. I don't see how this could not be of interest to the membership at large. I think the problem is that with the current process the only times prioritization is ever considered in some way is at the time of chartering or rechartering WGs. Within the charters it's up to the WGs themselves to figure out what they do, under the guidance of their chair(s).

The current situation suggests a need for additional checkpoints.

This being said, I think it is worth mentioning that the situation with the HTML WG in particular may also be that right now the browser vendors are not interested in developing the standard any further. If that's the case, we should simply acknowledge it and let the current charter expire until there is enough interest to charter a new WG.

**Comment by wayneca** [comment] 2015-05-22 18:37
The proposal wasn't about a meeting about the HTML WG.  It wasn't about any particular WG.  It was about priorities in general.  The refactoring part of the proposal could mean there isn't an HTML WG.

If the proposal had been that the HTML WG invites all implementers to a "panel" discussion quarterly to discuss their views, I don't think there would have been the objections there were.

What I didn't want is formalizing a special role for a particular, small set of companies where it looks like they jointly set policy and where participation is (severely) restricted.

If the HTML WG itself had calls where the purpose was to talk to the major Web Browser implementers, that would be fine.  Could be something like ask them questions.  They state their views.  Everyone in the WG can participate.

**Comment by plehegar** [comment] 2015-05-23 14:04
@lehors I believe there are 3 parts here: the CG, the WG(s), and the browser(s) meeting. Those 3 parts could be resolved independently and are pursuing different goals:
- The CG is to facilitate contributions of ideas from the the community at large.
- The WG(s) is to set up an efficient work mode that brings us towards greater interoperability.
- The browser(s) meeting is to ensure that a proper communication between the browser teams and W3C in general.

As @wcarr is pointing out, those browser meetings are not tied to the HTML WG in particular or a particular specification. It would be inappropriate to have such meeting outside the WG.

Removing it from the plan doesn't mean dropping it, but we shouldn't tight the fate of the HTML WG to it since those browser meetings aren't just about the HTML WG.

Yes, the need for proper _general_ communication and dialogue is still there but I don't have yet an alternative proposal and, in my mind, it is less of a priority than figuring the CG and proposing a plan for the WG(s). I believe I need to come back with a better framing of the scope and goals of those meetings first.

**Comment by plehegar** [comment] 2015-05-23 15:20
(btw, I should also point out that the idea of separating the browser meeting from the plan is my own and not representative of anyone else, within or outside W3C)

**Comment by rubys** [comment] 2015-06-03 17:54
Just so it is clear: -1 to decoupling the browser meetings from the HTML plan.

There is no way can any reasonable person position such meetings as "side meetings".  They are necessary.  They are front and center.  The results impact multiple groups.  

Accordingly, there should be a defined mechanism for those that are impacted to participate.  That does not mean that everybody who might conceivably be impacted has a right to be in the room.  But what it does mean is that stating up front that only browser vendors and W3C staff are allowed in the room is problematic.

**Comment by plehegar** [comment] 2015-06-12 18:40
An update on this front: a proposal related to the browser meetings is still being worked but will take until the second week of July at the very least. At this time, I'd expect it will differ substantially from the one proposed in the HTML plan.

**Comment by plehegar** [comment] 2015-10-08 19:28
At this point, the proposal has been dropped and no further action is expected to happen. This does mean no browser meetings.

**Closed as completed by plehegar** 2015-10-08 19:28 UTC
